name: Simple-Project CI/CD workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install -B

    - name: Dockerize SpringBoot Application
      run: |
        docker build -t simple-project .
        docker tag simple-project samjayworldwide/simple-project:latest
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push samjayworldwide/simple-project:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to Netlify
      uses: South-Paw/action-netlify-cli@v2
      with:
        args: deploy --prod --image samjayworldwide/simple-project:latest
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
